### ISSUE TITLE
No such option: --model

### ISSUE THREAD

**Issue by bariselci** [kfatehi/LamaCleaner.pinokio#2]
Hello kfatehi, i'm receiving the following error, how do we overcome it?

Microsoft Windows [Version 10.0.19045.4291]
(c) Microsoft Corporation. Tüm hakları saklıdır.

`D:\AIs\pinokio\api\LamaCleaner.pinokio.git\app>conda_hook && conda deactivate && conda deactivate && co
nda deactivate && conda activate base && D:\AIs\pinokio\api\LamaCleaner.pinokio.git\app\env\Scripts\act
ivate D:\AIs\pinokio\api\LamaCleaner.pinokio.git\app\env && python main.py --model=lama --device=cpu --
port=8080
Usage: main.py [OPTIONS] COMMAND [ARGS]...
Try 'main.py --help' for help.
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such option: --model Did you mean --help?                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯`

**Comment by poudi7** [comment]
Hi,

I have the same issue. I was able to make it run by adding `start` after main.py in the start.json file, but then got an error about a missing web_app folder. Creating the folder solved this error, and the server started. Unfortunately, all the page displays is `{"detail":"Not Found"}`.
I've run out of ideas to make it work. I even tried populating the web_app folder with the file from IOPAINT, but that did not work.
On a side note, it is possible to start the configuration server and change settings by adding `start-web-config` after main.py in start.json.

**Comment by kfatehi** [comment]
I see that the project has changed to IOPaint and has made major changes to its structure in the process.

I am not sure what the correct approach should be... for this pinokio package to be locked to a particular commit to increase chances of predictable builds? or to leave it to always be tracking the default branch (as it does currently) and break as it did?

Regardless, as a quick response, I have done the first option now. 

https://github.com/kfatehi/LamaCleaner.pinokio/commit/8f9d4d904bbcd9eef0671e2b068282e26b0ec85e

I do not have access to a test machine for this project at the moment, so I have opted for the first option (to hopefully at least make the package idempotent if at all possible) but I am not sure if it will work (e.g. the model it downloads might not exist anymore, or other unknown issues given it is now set to clone a 4 month old version of the project).

Feel free to try it out and see if it helps.

Ideally we would target a more recent commit and adapt to the structural changes (which do not seem totally obvious to me without the ability to conduct testing).

**Comment by poudi7** [comment]
I still had to add `start` after main.py for it to run
`"message": "python main.py start --model=lama --device=cpu --port=8080",`

This time, I don't get the error in the console.

```
Microsoft Windows [Version 10.0.22621.3447]
(c) Microsoft Corporation. All rights reserved.

C:\pinokio\api\LamaCleaner.pinokio.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\LamaCleaner.pinokio.git\app\env\Scripts\activate C:\pinokio\api\LamaCleaner.pinokio.git\app\env && python main.py start --model=lama --device=cpu --port=8080
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.14
- torch: 2.2.2
- torchvision: 0.17.2
- Pillow: 10.3.0
- diffusers: 0.23.0
- transformers: 4.34.1
- opencv-python: 4.9.0.80
- accelerate: N/A
- lama-cleaner: N/A
- rembg: 2.0.56
- realesrgan: 0.3.0
- gfpgan: 1.3.8

[W init.cpp:768] Warning: nvfuser is no longer supported in torch script, use _jit_set_nvfuser_enabled is deprecated and a no-op (function operator ())
2024-04-24 08:35:30.966 | INFO     | lama_cleaner.model_manager:init_model:30 - Loading model: lama
2024-04-24 08:35:30.966 | INFO     | lama_cleaner.helper:load_jit_model:102 - Loading model from: C:\pinokio\cache\TORCH_HOME\hub\checkpoints\big-lama.pt
Running on http://127.0.0.1:8080
Press CTRL+C to quit
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /static/js/main.1fda6320.js HTTP/1.1" 304 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /static/css/main.ce986cc8.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /inputimage HTTP/1.1" 200 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /is_desktop HTTP/1.1" 404 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /server_config HTTP/1.1" 200 -
[2024-04-24 08:35:34,633] ERROR in app: Exception on /model [GET]
Traceback (most recent call last):
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\lama_cleaner\server.py", line 441, in current_model 
    global_config.model_manager.current_model,
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\lama_cleaner\model_manager.py", line 27, in current_model
    return self.available_models[name].model_dump()
NameError: name 'name' is not defined
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /model HTTP/1.1" 500 -
127.0.0.1 - - [24/Apr/2024 08:35:34] "GET /static/media/Inter-roman.var.ba4caefcdf5b36b438db.woff2 HTTP/1.1" 304 -
[2024-04-24 08:35:37,298] ERROR in app: Exception on /model [GET]
Traceback (most recent call last):
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\lama_cleaner\server.py", line 441, in current_model 
    global_config.model_manager.current_model,
  File "C:\pinokio\api\LamaCleaner.pinokio.git\app\lama_cleaner\model_manager.py", line 27, in current_model
    return self.available_models[name].model_dump()
NameError: name 'name' is not defined
127.0.0.1 - - [24/Apr/2024 08:35:37] "GET /model HTTP/1.1" 500 -

```

The UI loads, I can upload an image, but when I attempt to erase, I get this error.
`cannot read strategy of undefined (reading 'hdStrategy')`

I couldn't find anything about this error, especially as it does not appear in the console.

**Comment by kfatehi** [comment]
Thanks for testing. I was able to reproduce your experience. I decided to target the latest version and simplify it significantly. It was not utilizing the GPU anyway, so I removed that, and rely on the instructions listed in IOPaint README which no longer requires cloning the project. Instead we simply install the pip package.

**Comment by poudi7** [comment]
So, this is what I get in the console when I install
```
Microsoft Windows [Version 10.0.22621.3447]
(c) Microsoft Corporation. All rights reserved.

C:\pinokio\api\IOPaint.pinokio.git>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && python -m venv C:\pinokio\api\IOPaint.pinokio.git\env && C:\pinokio\api\IOPaint.pinokio.git\env\Scripts\activate C:\pinokio\api\IOPaint.pinokio.git\env

(env) (base) C:\pinokio\api\IOPaint.pinokio.git>
```

And when I run it.

```
Microsoft Windows [Version 10.0.22621.3447]
(c) Microsoft Corporation. All rights reserved.

C:\pinokio\api\IOPaint.pinokio.git>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\IOPaint.pinokio.git\env\Scripts\activate C:\pinokio\api\IOPaint.pinokio.git\env && iopaint start --model=lama --device=cpu --port=8080
'iopaint' is not recognized as an internal or external command,
operable program or batch file.

(env) (base) C:\pinokio\api\IOPaint.pinokio.git>

```



So I tried to use [gepeto](https://github.com/cocktailpeanutlabs/gepeto) to create a blank container and then modified install.py and start.py to this.

Install.py
```
module.exports = {
  run: [
    // Delete this step if your project does not use torch
    {
      method: "script.start",
      params: {
        uri: "torch.js",
        params: {
          venv: "env",                // Edit this to customize the venv folder path
          // xformers: true   // uncomment this line if your project requires xformers
        }
      }
    },
    // Edit this step with your custom install commands
    {
      method: "shell.run",
      params: {
        venv: "env",                // Edit this to customize the venv folder path
        message: [
          "pip install -r requirements.txt",
          "pip3 install iopaint"
        ],
      }
    },
    //  Uncomment this step to add automatic venv deduplication (Experimental)
    //  {
    //    method: "fs.link",
    //    params: {
    //      venv: "env"
    //    }
    //  },
    {
      method: "notify",
      params: {
        html: "Click the 'start' tab to get started!"
      }
    }
  ]
}
```



start.py
```
module.exports = {
  daemon: true,
  run: [
    // Edit this step to customize your app's launch command
    {
      method: "shell.run",
      params: {
        venv: "env",                // Edit this to customize the venv folder path
        env: { },                   // Edit this to customize environment variables (see documentation)
        message: [
          "iopaint start --model=lama --device=cuda --port=8080",    // Edit with your custom commands
        ],
        on: [{
          // The regular expression pattern to monitor.
          // When this pattern occurs in the shell terminal, the shell will return,
          // and the script will go onto the next step.
          "event": "/http:\/\/\\S+/",   

          // "done": true will move to the next step while keeping the shell alive.
          // "kill": true will move to the next step after killing the shell.
          "done": true
        }]
      }
    },
    // This step sets the local variable 'url'.
    // This local variable will be used in pinokio.js to display the "Open WebUI" tab when the value is set.
    {
      method: "local.set",
      params: {
        // the input.event is the regular expression match object from the previous step
        url: "{{input.event[0]}}"
      }
    },
//    Uncomment this step to enable local wifi sharing (access the app from devices on the same network)
//    {
//      method: "proxy.start",
//      params: {
//        uri: "{{local.url}}",
//        name: "Local Sharing"
//      }
//    }
  ]
}
```


I have no idea why it wasn't required to install PyTorch before 'pip3 install iopaint' as noted [here](https://www.iopaint.com/install), but it seems like it installed it anyway, and it is functioning. I'm not sure it's the cleanest install as the reset button probably won't work, but that got it running.
